version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run:
          name: Insatlling Deps
          command: npm install
      - run: CI=true npm run build

  test:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run:
          name: Insatlling Deps
          command: npm install
      - run:
          name: Running Tests
          command: npm test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
